<!DOCTYPE html>
<html>
  <head>
    <title>Test Edit App</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  
  <body>
    <div class="container">
      <h1 class="text-center mt-5">Say it in your way</h1>
      
      <div class="form-group">
        <input type="text" class="form-control mx-auto w-50" value="" />
      </div>
      
      <div class="text-center">
        <input type="submit" class="btn btn-primary" value="Submit" />
      </div>
      
       <h1 class="text-center mt-5">Professionals say, </h1>
        <div class="form-group">
        <input type="text" class="form-control mx-auto w-50" value="${output}" />
      </div>
      
    </div>
  </body>
  
  

</html>
