<!DOCTYPE html>
<html>
  <head>
    <title>Test Edit App</title>
    <link rel="stylesheet" type="text/css" href="style.css">
  </head>
  <body>
    <h1>Say it in your way</h1>
    <div class="center">
      <input type="text" value="" id="input" />
       <input type="submit" value="Submit" />
    </div>
    
    <h1>Make it professional</h1>
    <div class="center">
      <input type="text" value="${output}"  id="output" />
    </div>
    
  </body>
</html>
